Repository wpi-25/gompei25, pull requests merged in 2021-11, with the labels that each got.

#24 Add fun commands
  Cargo.toml
  src/commands/fun.rs
  src/commands/mod.rs
  src/main.rs
Labels: enhancement

#26 Fix branch and tag selectors for Action
  .github/workflows/release.yml
Labels: bug, docker

#28 staff: Add modmail
  src/commands/fun.rs
  src/commands/leveling.rs
  src/commands/meta.rs
  src/commands/mod.rs
  src/commands/staff.rs
  src/errors.rs
  src/main.rs
  src/util/leveling.rs
Labels: enhancement

#32 Fix page numbering and rank numbering
  src/commands/leveling.rs
Labels: bug, high-priority
